### ISSUE TITLE
Fallo al ejecutar: java.lang.ClassNotFoundException: gui.Lanzador

### ISSUE THREAD

**Issue by fvarrui** [GabrielPerezMinik/MiCV#1]
```bash
$ mvn clean compile exec:java
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------< dad:MiCV >------------------------------
[INFO] Building MiCV 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MiCV ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MiCV ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to C:\Users\fvarrui\.Reviser\exercises\DAD-MiCV-149800\Gabriel González Jorge_1317772_assignsubmission_onlinetext_\files\MiCV\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.720 s
[INFO] Finished at: 2022-12-05T15:11:10Z
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------< dad:MiCV >------------------------------
[INFO] Building MiCV 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ MiCV ---
[WARNING] 
java.lang.ClassNotFoundException: gui.Lanzador
    at java.net.URLClassLoader.findClass (URLClassLoader.java:445)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:588)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:246)
    at java.lang.Thread.run (Thread.java:1589)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.918 s
[INFO] Finished at: 2022-12-05T15:11:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project MiCV: An exception occured while executing the Java class. gui.Lanzador -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Ha ocurrido un error: exec:java failed
java.lang.Exception: Fallo al ejecutar el proyecto (mvn exec:java). Revisa la propiedad 'exec.mainClass' del fichero pom.xml.
	at io.github.fvarrui.reviser.testers.Maven.test(Maven.java:36)
	at io.github.fvarrui.reviser.testers.Tester.runTest(Tester.java:22)
	at io.github.fvarrui.reviser.model.Submission.run(Submission.java:245)
	at io.github.fvarrui.reviser.ui.tasks.RunSubmissionTask.call(RunSubmissionTask.java:21)
	at io.github.fvarrui.reviser.ui.tasks.RunSubmissionTask.call(RunSubmissionTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by fvarrui** [comment]
Por cierto, ya lo arreglé yo para seguir probando, pero para que lo tengas en cuenta.

**Comment by GabrielPerezMinik** [comment]
Entiendo, gracias, disculpe las molestias, no me acorde de probar el maeven en este proyecto, ya esta corregido
